# Generated by Django 5.1.5 on 2025-01-30 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0004_alter_lesson_course"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_amount", models.IntegerField(verbose_name="сумма платежа")),
                (
                    "date_paymate",
                    models.DateField(auto_now=True, verbose_name="дата платежа"),
                ),
                (
                    "form_of_paymate",
                    models.CharField(
                        choices=[("Cash", "Наличные"), ("Card", "банковский перевод")],
                        default="Наличные",
                        verbose_name="Способ оплаты",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments_course",
                        to="materials.course",
                        verbose_name="course",
                    ),
                ),
                (
                    "lessons",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments_lesson",
                        to="materials.lesson",
                        verbose_name="lessons",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Платеж",
                "verbose_name_plural": "Платежи",
            },
        ),
    ]
