# Generated by Django 5.1.5 on 2025-01-30 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0004_alter_lesson_course"),
        ("users", "0002_payments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments_course",
                to="materials.course",
                verbose_name="course",
            ),
        ),
        migrations.AlterField(
            model_name="payments",
            name="lessons",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments_lesson",
                to="materials.lesson",
                verbose_name="lessons",
            ),
        ),
    ]
