# Generated by Django 5.1.5 on 2025-01-31 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_payments_course_alter_payments_lessons"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
