# Generated by Django 5.1.5 on 2025-01-20 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите навание курса",
                        max_length=25,
                        unique=True,
                        verbose_name="Название курса",
                    ),
                ),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        help_text="Превью курса",
                        null=True,
                        upload_to="materials/course",
                        verbose_name="Заставка",
                    ),
                ),
                (
                    "descriptions",
                    models.TextField(
                        blank=True, help_text="Введите описание курса.", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите навание урока",
                        max_length=25,
                        unique=True,
                        verbose_name="Название урока",
                    ),
                ),
                (
                    "descriptions",
                    models.TextField(
                        blank=True, help_text="Введите описание урока.", null=True
                    ),
                ),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        help_text="Превью курса",
                        null=True,
                        upload_to="materials/lesson",
                        verbose_name="Заставка",
                    ),
                ),
                ("video_url", models.URLField(blank=True, null=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="Course",
                        to="materials.course",
                    ),
                ),
            ],
            options={
                "verbose_name": "Урок",
                "verbose_name_plural": "Уроки",
            },
        ),
    ]
