# Generated by Django 5.1.5 on 2025-02-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0008_coursepayment"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.PositiveIntegerField(default=100, verbose_name="Цена"),
        ),
    ]
